import Head from "next/head";
import Menu from "./menu"
import style from '../../aprendo-nextjs/src/styles/layout.module.css';
export default function Layout({children, title} ) {
  return (
    <div>
      <Head>
        <title>GitHub Merch {title ? `| ${title}` : ""}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menu>
        


      </Menu>
        <div className={style.container}>
            {children}
        </div>

    </div>
  );
}
